### ISSUE TITLE
Messages takes half hour or more than before i received

### ISSUE THREAD

**Issue by code302** [webreinvent/tempemails#1]
please fix the problem

**Comment by themodernpk** [comment]
@code302 we'll be working on this issue today. Will be fixed by EOD. Thanks for reporting.

**Comment by code302** [comment]
thanks a lot i rely need your tempmail

**Comment by code302** [comment]
if it's ok please deliver my confirmation link this email
nvijs@tempemails.io

**Comment by code302** [comment]
if it's ok please deliver my confirmation link this email
uxr12@tempemails.io

**Comment by themodernpk** [comment]
Speed and loading issues are fixed
