### ISSUE TITLE
can not login old email

### ISSUE THREAD

**Issue by code302** [webreinvent/tempemails#3]
please admin fix this issue i can't login my old email that i used i need to login that because the site i used need to send confirmation link there, and i can't open the site without confirmation code

**Comment by themodernpk** [comment]
@code302 previous emails were lost during the upgrade and can't be recovered.

**Comment by code302** [comment]
and why it say email already exist?

**Comment by code302** [comment]
please i want to login this email
scott@tempemails.io 100
jessica@tempemails.io 100
brenda@tempemails.io 100
nedra@tempemails.io 100
mae@tempemails.io 100
sally@tempemails.io 100
lillian@tempemails.io 100
xaorc@tempemails.io 100

**Comment by themodernpk** [comment]
If you are not using the same system/computer or clear your cache, the application will not detect and will start the complete new session. It is recommended to note your url like ```https://tempemails.io/<unique-code>/apps``` to access the same email accounts.

**Comment by code302** [comment]
Im using different computer and it is the same problem say "already in used"

**Comment by code302** [comment]
can you please change also the "io" domain because digital ocean need now
fresh email and "io" domain is already detected in their system

**Comment by themodernpk** [comment]
@code302 you need to understand that the tool is developed for testing purpose only, not for the real world usages. Also, this is a free tool and support is limited. Hope you understand. Thanks

**Comment by code302** [comment]
please fix the issue i want to login that email
